server:
  port: 8083

spring:
  application:
    name: eshop-cart-service
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 3000
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        ip: 127.0.0.1

# Feign 配置
feign:
  client:
    config:
      eshop-product-service:
        connect-timeout: 3000
        read-timeout: 5000

logging:
  level:
    com.eshop.cart.feign: DEBUG

# Sentinel 熔断降级
spring.cloud.sentinel:
  transport:
    dashboard: localhost:8718
spring.cloud.openfeign.sentinel.enabled: true
